dockerfile: |-
  RUN apk add --no-cache build-base git mariadb-client mariadb-dev
  RUN gem install gem_hadar

script: &script |-
  echo -e "\e[1m"
  ruby -v
  echo -e "\e[0m"
  bundle install --full-index
  bundle exec rake test

fail_fast: yes

env:
  - DATABASE_URL=mysql2://root@host.docker.internal:3336/test

images:
  ruby:3.4-alpine: *script
  ruby:3.3-alpine: *script
