dockerfile: |-
  RUN apk add --no-cache build-base yaml-dev git openssl-dev mariadb-client mariadb-dev
  RUN gem update --system
  RUN gem install bundler gem_hadar

script: &script |-
  echo -e "\e[1m"
  ruby -v
  echo -e "\e[0m"
  bundle update --all
  bundle install --jobs=$(getconf _NPROCESSORS_ONLN)
  bundle exec rake test

fail_fast: yes

env:
  - MARIADB_TLS_DISABLE_PEER_VERIFICATION=1
  - DATABASE_URL=mysql2://root@host.docker.internal:3336/test

images:
  ruby:4.0-alpine: *script
  ruby:3.4-alpine: *script
  ruby:3.3-alpine: *script
